import os
import sqlite3
import time
import math
import hmac
import secrets
import threading
from datetime import datetime, timedelta, timezone
from flask import Flask, jsonify, request, send_from_directory
from flask import session

# ==========================================
# KONFIGURASI APLIKASI
# ==========================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')
FRONTEND_ASSETS_DIR = os.path.join(FRONTEND_DIR, 'assets')


def load_local_environment():
    env_file = os.path.join(BASE_DIR, '.env')
    if not os.path.isfile(env_file):
        return
    with open(env_file, encoding='utf-8') as file:
        for line in file:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            if key and key not in os.environ:
                os.environ[key] = value.strip().strip('"').strip("'")


load_local_environment()

IS_PRODUCTION = (
    os.environ.get('ENVIRONMENT', '').lower() == 'production'
    or os.environ.get('VERCEL') == '1'
)
app = Flask(__name__)
app.secret_key = os.environ.get('FLASK_SECRET_KEY') or (
    None if IS_PRODUCTION else secrets.token_hex(32)
)
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE='Lax',
    SESSION_COOKIE_SECURE=IS_PRODUCTION,
    PERMANENT_SESSION_LIFETIME=timedelta(hours=8),
)

DB_FILE = os.path.join(BASE_DIR, "db_kost_manov.db")
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
DEFAULT_TARIF = 1500 # Rp per kWh
ROOMS = (
    ('01', 'Yakop'),
    ('02', 'Pian'),
    ('03', 'Rehan'),
    ('04', 'Topek'),
    ('05', 'Belum diisi'),
)
SENSOR_ONLINE_SECONDS = 15
MAX_INTEGRATION_SECONDS = 60

# ==========================================
# DATABASE
# ==========================================
class DatabaseConfigurationError(RuntimeError):
    pass


class DatabaseConnection:
    def __init__(self, connection, postgres=False):
        self.connection = connection
        self.postgres = postgres
        self.cursor_result = None

    def cursor(self):
        return self

    def execute(self, query, parameters=()):
        if self.postgres:
            query = query.replace('?', '%s')
            self.cursor_result = self.connection.cursor()
            self.cursor_result.execute(query, parameters)
        else:
            self.cursor_result = self.connection.execute(query, parameters)
        return self.cursor_result

    def fetchone(self):
        return self.cursor_result.fetchone()

    def fetchall(self):
        return self.cursor_result.fetchall()

    def commit(self):
        self.connection.commit()

    def close(self):
        self.connection.close()


def get_db_connection():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        database_url = DATABASE_URL
        if database_url.startswith('postgres://'):
            database_url = 'postgresql://' + database_url.removeprefix('postgres://')
        connection = psycopg.connect(database_url, row_factory=dict_row, connect_timeout=10)
        return DatabaseConnection(connection, postgres=True)

    if IS_PRODUCTION:
        raise DatabaseConfigurationError(
            'DATABASE_URL belum dikonfigurasi. Tambahkan connection string PostgreSQL '
            'pada environment variables deployment.'
        )
    connection = sqlite3.connect(DB_FILE, timeout=10)
    connection.row_factory = sqlite3.Row
    return DatabaseConnection(connection)


def calculate_power_w(voltage_v, current_a, power_factor=1.0):
    return voltage_v * current_a * power_factor


def calculate_consumption_kwh(power_w, elapsed_seconds):
    return power_w * elapsed_seconds / 3_600_000


def current_billing_period():
    jakarta_now = datetime.now(timezone.utc) + timedelta(hours=7)
    return jakarta_now.strftime('%Y-%m')


def init_db():
    conn = get_db_connection()
    c = conn.cursor()
    
    c.execute('''CREATE TABLE IF NOT EXISTS settings (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL)''')
    
    c.execute(
        "INSERT INTO settings (key, value) VALUES ('tarif', ?) ON CONFLICT (key) DO NOTHING",
        (str(DEFAULT_TARIF),)
    )
    c.execute(
        "INSERT INTO settings (key, value) VALUES ('billing_period', ?) ON CONFLICT (key) DO NOTHING",
        (current_billing_period(),)
    )

    if conn.postgres:
        c.execute('''CREATE TABLE IF NOT EXISTS kamar (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nomor TEXT UNIQUE NOT NULL,
                        penghuni TEXT,
                        voltage_v DOUBLE PRECISION DEFAULT 0,
                        current_a DOUBLE PRECISION DEFAULT 0,
                        power_factor DOUBLE PRECISION DEFAULT 1,
                        daya_watt DOUBLE PRECISION DEFAULT 0,
                        total_kwh DOUBLE PRECISION DEFAULT 0,
                        total_biaya DOUBLE PRECISION DEFAULT 0,
                        last_reading_at DOUBLE PRECISION DEFAULT 0)''')
        existing_columns = {
            row['name'] for row in c.execute(
                "SELECT column_name AS name FROM information_schema.columns WHERE table_name='kamar'"
            ).fetchall()
        }
    else:
        c.execute('''CREATE TABLE IF NOT EXISTS kamar (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        nomor TEXT UNIQUE NOT NULL,
                        penghuni TEXT,
                        voltage_v REAL DEFAULT 0,
                        current_a REAL DEFAULT 0,
                        power_factor REAL DEFAULT 1,
                        daya_watt REAL DEFAULT 0,
                        total_kwh REAL DEFAULT 0,
                        total_biaya REAL DEFAULT 0,
                        last_reading_at REAL DEFAULT 0)''')
        existing_columns = {row['name'] for row in c.execute("PRAGMA table_info(kamar)").fetchall()}
    measurement_type = 'DOUBLE PRECISION' if conn.postgres else 'REAL'
    new_columns = {
        'voltage_v': f'{measurement_type} DEFAULT 0',
        'current_a': f'{measurement_type} DEFAULT 0',
        'power_factor': f'{measurement_type} DEFAULT 1',
        'last_reading_at': f'{measurement_type} DEFAULT 0',
    }
    for column, definition in new_columns.items():
        if column not in existing_columns:
            c.execute(f"ALTER TABLE kamar ADD COLUMN {column} {definition}")

    allowed_rooms = tuple(room[0] for room in ROOMS)
    placeholders = ','.join('?' for _ in allowed_rooms)
    c.execute(f"DELETE FROM kamar WHERE nomor NOT IN ({placeholders})", allowed_rooms)
    for room in ROOMS:
        c.execute(
            "INSERT INTO kamar (nomor, penghuni) VALUES (?, ?) ON CONFLICT (nomor) DO NOTHING",
            room
        )

    sensor_mode = c.execute(
        "SELECT value FROM settings WHERE key='sensor_mode_version'"
    ).fetchone()
    if sensor_mode is None:
        c.execute(
            """UPDATE kamar
               SET voltage_v=0, current_a=0, power_factor=1, daya_watt=0,
                   total_kwh=0, total_biaya=0, last_reading_at=0"""
        )
        c.execute(
            "INSERT INTO settings (key, value) VALUES ('sensor_mode_version', '1') ON CONFLICT (key) DO NOTHING"
        )
        
    conn.commit()
    conn.close()
    print(f"[DB] Database siap di: {DB_FILE}")


_database_initialized = False
_database_initialization_lock = threading.Lock()


def ensure_database_initialized():
    global _database_initialized
    if _database_initialized:
        return
    with _database_initialization_lock:
        if not _database_initialized:
            init_db()
            _database_initialized = True


def ensure_current_billing_period():
    period = current_billing_period()
    conn = get_db_connection()
    try:
        changed_period = conn.execute(
            "UPDATE settings SET value=? WHERE key='billing_period' AND value<>?",
            (period, period)
        )
        if changed_period.rowcount:
            conn.execute("UPDATE kamar SET total_kwh=0, total_biaya=0")
            conn.commit()
    finally:
        conn.close()


def auth_configuration_error():
    missing = []
    if not app.secret_key:
        missing.append('FLASK_SECRET_KEY')
    if not os.environ.get('SITE_LOGIN_PASSWORD'):
        missing.append('SITE_LOGIN_PASSWORD')
    if missing:
        return jsonify({
            'error': f'Konfigurasi login belum lengkap. Atur: {", ".join(missing)}.'
        }), 503
    return None


# ==========================================
# ROUTING & API FLASK
# ==========================================
@app.route('/')
def index():
    return send_from_directory(FRONTEND_DIR, 'index.html')


@app.route('/assets/<path:filename>')
def frontend_assets(filename):
    return send_from_directory(FRONTEND_ASSETS_DIR, filename)


@app.route('/api/health', methods=['GET'])
def health_check():
    ensure_database_initialized()
    conn = get_db_connection()
    try:
        conn.execute("SELECT 1")
    finally:
        conn.close()
    return jsonify({'status': 'ok'})


@app.before_request
def handle_cors_preflight():
    if request.method != 'OPTIONS':
        return None
    origin = request.headers.get('Origin', '')
    if origin not in allowed_origins():
        return jsonify({'error': 'Origin tidak diizinkan.'}), 403
    return '', 204


@app.before_request
def require_site_login():
    public_paths = {
        '/api/auth/status',
        '/api/login',
        '/api/logout',
        '/api/health',
        '/api/sensor/reading',
    }
    if request.path.startswith('/api/') and request.path not in public_paths:
        configuration_error = auth_configuration_error()
        if configuration_error:
            return configuration_error
        if not session.get('site_authenticated'):
            return jsonify({'error': 'Silakan login terlebih dahulu.'}), 401
    return None


@app.after_request
def add_cors_headers(response):
    origin = request.headers.get('Origin', '')
    if origin in allowed_origins():
        response.headers['Access-Control-Allow-Origin'] = origin
        response.headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, OPTIONS'
        response.headers['Access-Control-Allow-Headers'] = 'Content-Type, X-Sensor-Key'
        response.headers['Access-Control-Allow-Credentials'] = 'true'
        response.headers['Access-Control-Max-Age'] = '600'
        response.headers.add('Vary', 'Origin')
    return response


def allowed_origins():
    origins = {
        origin.strip().rstrip('/')
        for origin in os.environ.get('ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    }
    if not IS_PRODUCTION:
        origins.update({'http://localhost:5000', 'http://127.0.0.1:5000'})
    return origins


def require_api_key(environment_variable, header_name):
    configured_key = os.environ.get(environment_variable, '')
    if not configured_key:
        if IS_PRODUCTION or environment_variable == 'ADMIN_API_KEY':
            return jsonify({'status': 'gagal', 'error': f'{environment_variable} belum dikonfigurasi.'}), 503
        return None

    supplied_key = request.headers.get(header_name, '')
    if not hmac.compare_digest(supplied_key, configured_key):
        return jsonify({'status': 'gagal', 'error': 'Kunci akses tidak valid.'}), 401
    return None


@app.route('/api/admin/verify', methods=['POST'])
def verify_admin_access():
    if not session.get('site_authenticated'):
        return jsonify({'error': 'Silakan login terlebih dahulu.'}), 401

    admin_key = os.environ.get('ADMIN_API_KEY', '')
    if not admin_key:
        return jsonify({'error': 'ADMIN_API_KEY belum dikonfigurasi di environment Vercel.'}), 503

    data = request.get_json(silent=True)
    supplied_key = data.get('password') if isinstance(data, dict) else None
    if not isinstance(supplied_key, str) or not hmac.compare_digest(supplied_key, admin_key):
        session.pop('admin_verified', None)
        return jsonify({'error': 'Sandi admin tidak valid.'}), 401

    session['admin_verified'] = True
    return jsonify({'status': 'sukses'})


@app.route('/api/auth/status', methods=['GET'])
def auth_status():
    configuration_error = auth_configuration_error()
    if configuration_error:
        return configuration_error
    return jsonify({'authenticated': bool(session.get('site_authenticated'))})


@app.route('/api/login', methods=['POST'])
def login():
    configuration_error = auth_configuration_error()
    if configuration_error:
        return configuration_error

    data = request.get_json(silent=True)
    password = data.get('password') if isinstance(data, dict) else None
    configured_password = os.environ['SITE_LOGIN_PASSWORD']
    if not isinstance(password, str) or not hmac.compare_digest(password, configured_password):
        return jsonify({'error': 'Kata sandi tidak valid.'}), 401

    session.clear()
    session.permanent = True
    session['site_authenticated'] = True
    return jsonify({'status': 'sukses'})


@app.route('/api/logout', methods=['POST'])
def logout():
    configuration_error = auth_configuration_error()
    if configuration_error:
        return configuration_error
    session.clear()
    return jsonify({'status': 'sukses'})


@app.route('/api/data', methods=['GET'])
def get_data():
    ensure_database_initialized()
    ensure_current_billing_period()
    conn = get_db_connection()
    try:
        tarif = float(conn.execute("SELECT value FROM settings WHERE key='tarif'").fetchone()['value'])
        kamar_rows = conn.execute("SELECT * FROM kamar ORDER BY nomor").fetchall()

        kamar_list = []
        total_semua_watt = 0
        total_semua_kwh = 0
        total_semua_biaya = 0
        waktu_sekarang = time.time()

        for row in kamar_rows:
            k = dict(row)
            k.pop('status_hidup', None)
            k['daya_watt'] = calculate_power_w(k['voltage_v'], k['current_a'], k['power_factor'])
            k['biaya_kalkulasi'] = round(k['total_kwh'] * tarif, 2)
            k['sensor_online'] = (
                k['last_reading_at'] > 0
                and waktu_sekarang - k['last_reading_at'] <= SENSOR_ONLINE_SECONDS
            )
            if k['sensor_online']:
                total_semua_watt += k['daya_watt']
            total_semua_kwh += k['total_kwh']
            total_semua_biaya += k['biaya_kalkulasi']
            kamar_list.append(k)
    finally:
        conn.close()
    
    return jsonify({
        'tarif_per_kwh': tarif,
        'kamar': kamar_list,
        'summary': {
            'total_watt': round(total_semua_watt, 2),
            'total_kwh': round(total_semua_kwh, 4),
            'total_biaya': round(total_semua_biaya, 2)
        }
    })

@app.route('/api/sensor/reading', methods=['POST'])
def receive_sensor_reading():
    """Accept an ESP32 reading.

    Deploy instructions and an Arduino HTTPClient example are in README-DEPLOY.md.
    Post nomor, voltage_v, current_a, and optional power_factor as JSON to this
    endpoint, with the X-Sensor-Key header set to the Render SENSOR_API_KEY.
    """
    auth_error = require_api_key('SENSOR_API_KEY', 'X-Sensor-Key')
    if auth_error:
        return auth_error

    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({'status': 'gagal', 'error': 'Kirim data dalam format JSON.'}), 400

    nomor = data.get('nomor')
    if not isinstance(nomor, str) or nomor not in {room[0] for room in ROOMS}:
        return jsonify({'status': 'gagal', 'error': 'Nomor kamar harus 01 sampai 05.'}), 400

    readings = {}
    for field, minimum, maximum in (
        ('voltage_v', 0, 1000),
        ('current_a', 0, 1000),
        ('power_factor', 0, 1),
    ):
        value = data.get(field, 1.0 if field == 'power_factor' else None)
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return jsonify({'status': 'gagal', 'error': f'{field} harus berupa angka.'}), 400
        if not math.isfinite(value) or not minimum <= value <= maximum:
            return jsonify({'status': 'gagal', 'error': f'{field} di luar rentang yang diizinkan.'}), 400
        readings[field] = float(value)

    ensure_database_initialized()
    ensure_current_billing_period()
    waktu_baca = time.time()
    conn = get_db_connection()
    try:
        room = conn.execute("SELECT * FROM kamar WHERE nomor=?", (nomor,)).fetchone()
        if room is None:
            return jsonify({'status': 'gagal', 'error': 'Kamar tidak ditemukan.'}), 404

        daya_watt = calculate_power_w(
            readings['voltage_v'], readings['current_a'], readings['power_factor']
        )
        elapsed_seconds = min(
            max(0, waktu_baca - room['last_reading_at']),
            MAX_INTEGRATION_SECONDS
        ) if room['last_reading_at'] else 0
        daya_sebelumnya = room['daya_watt'] if room['last_reading_at'] else daya_watt
        total_kwh = room['total_kwh'] + calculate_consumption_kwh(
            (daya_sebelumnya + daya_watt) / 2,
            elapsed_seconds
        )

        conn.execute(
            """UPDATE kamar
               SET voltage_v=?, current_a=?, power_factor=?, daya_watt=?,
                   total_kwh=?, last_reading_at=?
               WHERE nomor=?""",
            (
                readings['voltage_v'], readings['current_a'], readings['power_factor'],
                daya_watt, total_kwh, waktu_baca, nomor
            )
        )
        conn.commit()
    finally:
        conn.close()

    return jsonify({'status': 'sukses', 'nomor': nomor, 'daya_watt': round(daya_watt, 2)})

@app.route('/api/kamar/<nomor>/penghuni', methods=['PUT'])
def update_tenant(nomor):
    if not session.pop('admin_verified', False):
        return jsonify({'error': 'Masukkan sandi admin sebelum mengubah nama penghuni.'}), 401

    if nomor not in {room[0] for room in ROOMS}:
        return jsonify({'status': 'gagal', 'error': 'Nomor kamar harus 01 sampai 05.'}), 404

    data = request.get_json(silent=True)
    nama = data.get('penghuni') if isinstance(data, dict) else None
    if not isinstance(nama, str) or not nama.strip() or len(nama.strip()) > 80:
        return jsonify({'status': 'gagal', 'error': 'Nama penghuni wajib diisi (maksimal 80 karakter).'}), 400

    ensure_database_initialized()
    conn = get_db_connection()
    try:
        result = conn.execute(
            "UPDATE kamar SET penghuni=? WHERE nomor=?",
            (nama.strip(), nomor)
        )
        if result.rowcount == 0:
            return jsonify({'status': 'gagal', 'error': 'Kamar tidak ditemukan.'}), 404
        conn.commit()
    finally:
        conn.close()
    return jsonify({'status': 'sukses', 'nomor': nomor, 'penghuni': nama.strip()})

@app.route('/api/tarif', methods=['POST'])
def set_tarif():
    if not session.pop('admin_verified', False):
        return jsonify({'error': 'Masukkan sandi admin sebelum mengubah tarif.'}), 401

    data = request.get_json(silent=True)
    tarif_baru = data.get('tarif') if isinstance(data, dict) else None
    if isinstance(tarif_baru, (int, float)) and not isinstance(tarif_baru, bool) and math.isfinite(tarif_baru) and tarif_baru > 0:
        ensure_database_initialized()
        conn = get_db_connection()
        try:
            conn.execute("UPDATE settings SET value=? WHERE key='tarif'", (str(tarif_baru),))
            conn.commit()
        finally:
            conn.close()
        return jsonify({'status': 'sukses', 'tarif': tarif_baru})
    return jsonify({'status': 'gagal', 'error': 'Tarif harus berupa angka lebih besar dari nol.'}), 400


@app.errorhandler(500)
def handle_server_error(error):
    app.logger.exception("Unhandled dashboard error", exc_info=error)
    return jsonify({'error': 'Terjadi kesalahan internal pada server.'}), 500


@app.errorhandler(DatabaseConfigurationError)
def handle_database_configuration_error(error):
    app.logger.error("Database configuration error: %s", error)
    return jsonify({'error': str(error)}), 503


# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == '__main__':
    print("==========================================")
    print("Menyiapkan Database...")
    init_db()
    _database_initialized = True

    print("==========================================")
    print("WEB MONITORING SIAP!")
    print("Buka browser dan kunjungi: http://localhost:5000")
    print("Endpoint ESP32: POST http://<IP-LAPTOP>:5000/api/sensor/reading")
    print("==========================================")
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', '5000')), debug=False)
